# [2016-11-27] Auto-generated file, do not edit

PRODUCT_COPY_FILES += \
    vendor/huawei/angler/proprietary/bin/ATFWD-daemon:$(TARGET_COPY_OUT_SYSTEM)/bin/ATFWD-daemon:huawei \
    vendor/huawei/angler/proprietary/bin/cnd:$(TARGET_COPY_OUT_SYSTEM)/bin/cnd:huawei \
    vendor/huawei/angler/proprietary/bin/diag_callback_client:$(TARGET_COPY_OUT_SYSTEM)/bin/diag_callback_client:huawei \
    vendor/huawei/angler/proprietary/bin/diag_dci_sample:$(TARGET_COPY_OUT_SYSTEM)/bin/diag_dci_sample:huawei \
    vendor/huawei/angler/proprietary/bin/diag_klog:$(TARGET_COPY_OUT_SYSTEM)/bin/diag_klog:huawei \
    vendor/huawei/angler/proprietary/bin/diag_mdlog:$(TARGET_COPY_OUT_SYSTEM)/bin/diag_mdlog:huawei \
    vendor/huawei/angler/proprietary/bin/diag_qshrink4_daemon:$(TARGET_COPY_OUT_SYSTEM)/bin/diag_qshrink4_daemon:huawei \
    vendor/huawei/angler/proprietary/bin/diag_socket_log:$(TARGET_COPY_OUT_SYSTEM)/bin/diag_socket_log:huawei \
    vendor/huawei/angler/proprietary/bin/diag_uart_log:$(TARGET_COPY_OUT_SYSTEM)/bin/diag_uart_log:huawei \
    vendor/huawei/angler/proprietary/bin/dsm_ctrl:$(TARGET_COPY_OUT_SYSTEM)/bin/dsm_ctrl:huawei \
    vendor/huawei/angler/proprietary/bin/fingerprintd:$(TARGET_COPY_OUT_SYSTEM)/bin/fingerprintd:huawei \
    vendor/huawei/angler/proprietary/bin/imscmservice:$(TARGET_COPY_OUT_SYSTEM)/bin/imscmservice:huawei \
    vendor/huawei/angler/proprietary/bin/imsdatadaemon:$(TARGET_COPY_OUT_SYSTEM)/bin/imsdatadaemon:huawei \
    vendor/huawei/angler/proprietary/bin/imsqmidaemon:$(TARGET_COPY_OUT_SYSTEM)/bin/imsqmidaemon:huawei \
    vendor/huawei/angler/proprietary/bin/ims_rtp_daemon:$(TARGET_COPY_OUT_SYSTEM)/bin/ims_rtp_daemon:huawei \
    vendor/huawei/angler/proprietary/bin/irsc_util:$(TARGET_COPY_OUT_SYSTEM)/bin/irsc_util:huawei \
    vendor/huawei/angler/proprietary/bin/loc_launcher:$(TARGET_COPY_OUT_SYSTEM)/bin/loc_launcher:huawei \
    vendor/huawei/angler/proprietary/bin/mm-pp-daemon:$(TARGET_COPY_OUT_SYSTEM)/bin/mm-pp-daemon:huawei \
    vendor/huawei/angler/proprietary/bin/mm-qcamera-app:$(TARGET_COPY_OUT_SYSTEM)/bin/mm-qcamera-app:huawei \
    vendor/huawei/angler/proprietary/bin/mm-qjpeg-dec-test:$(TARGET_COPY_OUT_SYSTEM)/bin/mm-qjpeg-dec-test:huawei \
    vendor/huawei/angler/proprietary/bin/mm-qjpeg-enc-test:$(TARGET_COPY_OUT_SYSTEM)/bin/mm-qjpeg-enc-test:huawei \
    vendor/huawei/angler/proprietary/bin/mm-qomx-idec-test:$(TARGET_COPY_OUT_SYSTEM)/bin/mm-qomx-idec-test:huawei \
    vendor/huawei/angler/proprietary/bin/mm-qomx-ienc-test:$(TARGET_COPY_OUT_SYSTEM)/bin/mm-qomx-ienc-test:huawei \
    vendor/huawei/angler/proprietary/bin/msm_irqbalance:$(TARGET_COPY_OUT_SYSTEM)/bin/msm_irqbalance:huawei \
    vendor/huawei/angler/proprietary/bin/netmgrd:$(TARGET_COPY_OUT_SYSTEM)/bin/netmgrd:huawei \
    vendor/huawei/angler/proprietary/bin/nl_listener:$(TARGET_COPY_OUT_SYSTEM)/bin/nl_listener:huawei \
    vendor/huawei/angler/proprietary/bin/perfd:$(TARGET_COPY_OUT_SYSTEM)/bin/perfd:huawei \
    vendor/huawei/angler/proprietary/bin/PktRspTest:$(TARGET_COPY_OUT_SYSTEM)/bin/PktRspTest:huawei \
    vendor/huawei/angler/proprietary/bin/pm-proxy:$(TARGET_COPY_OUT_SYSTEM)/bin/pm-proxy:huawei \
    vendor/huawei/angler/proprietary/bin/pm-service:$(TARGET_COPY_OUT_SYSTEM)/bin/pm-service:huawei \
    vendor/huawei/angler/proprietary/bin/port-bridge:$(TARGET_COPY_OUT_SYSTEM)/bin/port-bridge:huawei \
    vendor/huawei/angler/proprietary/bin/qjpeg-dma-test:$(TARGET_COPY_OUT_SYSTEM)/bin/qjpeg-dma-test:huawei \
    vendor/huawei/angler/proprietary/bin/qmuxd:$(TARGET_COPY_OUT_SYSTEM)/bin/qmuxd:huawei \
    vendor/huawei/angler/proprietary/bin/radish:$(TARGET_COPY_OUT_SYSTEM)/bin/radish:huawei \
    vendor/huawei/angler/proprietary/bin/rmt_storage:$(TARGET_COPY_OUT_SYSTEM)/bin/rmt_storage:huawei \
    vendor/huawei/angler/proprietary/bin/ssr_setup:$(TARGET_COPY_OUT_SYSTEM)/bin/ssr_setup:huawei \
    vendor/huawei/angler/proprietary/bin/subsystem_ramdump:$(TARGET_COPY_OUT_SYSTEM)/bin/subsystem_ramdump:huawei \
    vendor/huawei/angler/proprietary/bin/test_diag:$(TARGET_COPY_OUT_SYSTEM)/bin/test_diag:huawei \
    vendor/huawei/angler/proprietary/bin/test_module_pproc:$(TARGET_COPY_OUT_SYSTEM)/bin/test_module_pproc:huawei \
    vendor/huawei/angler/proprietary/bin/thermal-engine:$(TARGET_COPY_OUT_SYSTEM)/bin/thermal-engine:huawei \
    vendor/huawei/angler/proprietary/bin/time_daemon:$(TARGET_COPY_OUT_SYSTEM)/bin/time_daemon:huawei \
    vendor/huawei/angler/proprietary/etc/acdbdata/angler/Angler_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/angler/Angler_Bluetooth_cal.acdb:huawei \
    vendor/huawei/angler/proprietary/etc/acdbdata/angler/Angler_General_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/angler/Angler_General_cal.acdb:huawei \
    vendor/huawei/angler/proprietary/etc/acdbdata/angler/Angler_Global_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/angler/Angler_Global_cal.acdb:huawei \
    vendor/huawei/angler/proprietary/etc/acdbdata/angler/Angler_Handset_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/angler/Angler_Handset_cal.acdb:huawei \
    vendor/huawei/angler/proprietary/etc/acdbdata/angler/Angler_Hdmi_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/angler/Angler_Hdmi_cal.acdb:huawei \
    vendor/huawei/angler/proprietary/etc/acdbdata/angler/Angler_Headset_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/angler/Angler_Headset_cal.acdb:huawei \
    vendor/huawei/angler/proprietary/etc/acdbdata/angler/Angler_Speaker_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/angler/Angler_Speaker_cal.acdb:huawei \
    vendor/huawei/angler/proprietary/etc/acdbdata/Fluid/Fluid_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/Fluid/Fluid_Bluetooth_cal.acdb:huawei \
    vendor/huawei/angler/proprietary/etc/acdbdata/Fluid/Fluid_General_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/Fluid/Fluid_General_cal.acdb:huawei \
    vendor/huawei/angler/proprietary/etc/acdbdata/Fluid/Fluid_Global_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/Fluid/Fluid_Global_cal.acdb:huawei \
    vendor/huawei/angler/proprietary/etc/acdbdata/Fluid/Fluid_Handset_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/Fluid/Fluid_Handset_cal.acdb:huawei \
    vendor/huawei/angler/proprietary/etc/acdbdata/Fluid/Fluid_Hdmi_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/Fluid/Fluid_Hdmi_cal.acdb:huawei \
    vendor/huawei/angler/proprietary/etc/acdbdata/Fluid/Fluid_Headset_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/Fluid/Fluid_Headset_cal.acdb:huawei \
    vendor/huawei/angler/proprietary/etc/acdbdata/Fluid/Fluid_Speaker_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/Fluid/Fluid_Speaker_cal.acdb:huawei \
    vendor/huawei/angler/proprietary/etc/acdbdata/Liquid/Liquid_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/Liquid/Liquid_Bluetooth_cal.acdb:huawei \
    vendor/huawei/angler/proprietary/etc/acdbdata/Liquid/Liquid_General_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/Liquid/Liquid_General_cal.acdb:huawei \
    vendor/huawei/angler/proprietary/etc/acdbdata/Liquid/Liquid_Global_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/Liquid/Liquid_Global_cal.acdb:huawei \
    vendor/huawei/angler/proprietary/etc/acdbdata/Liquid/Liquid_Handset_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/Liquid/Liquid_Handset_cal.acdb:huawei \
    vendor/huawei/angler/proprietary/etc/acdbdata/Liquid/Liquid_Hdmi_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/Liquid/Liquid_Hdmi_cal.acdb:huawei \
    vendor/huawei/angler/proprietary/etc/acdbdata/Liquid/Liquid_Headset_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/Liquid/Liquid_Headset_cal.acdb:huawei \
    vendor/huawei/angler/proprietary/etc/acdbdata/Liquid/Liquid_Speaker_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/Liquid/Liquid_Speaker_cal.acdb:huawei \
    vendor/huawei/angler/proprietary/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb:huawei \
    vendor/huawei/angler/proprietary/etc/acdbdata/MTP/MTP_General_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/MTP/MTP_General_cal.acdb:huawei \
    vendor/huawei/angler/proprietary/etc/acdbdata/MTP/MTP_Global_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/MTP/MTP_Global_cal.acdb:huawei \
    vendor/huawei/angler/proprietary/etc/acdbdata/MTP/MTP_Handset_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/MTP/MTP_Handset_cal.acdb:huawei \
    vendor/huawei/angler/proprietary/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb:huawei \
    vendor/huawei/angler/proprietary/etc/acdbdata/MTP/MTP_Headset_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/MTP/MTP_Headset_cal.acdb:huawei \
    vendor/huawei/angler/proprietary/etc/acdbdata/MTP/MTP_Speaker_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/MTP/MTP_Speaker_cal.acdb:huawei \
    vendor/huawei/angler/proprietary/etc/cne/profile.txt:$(TARGET_COPY_OUT_SYSTEM)/etc/cne/profile.txt:huawei \
    vendor/huawei/angler/proprietary/etc/data/dsi_config.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/data/dsi_config.xml:huawei \
    vendor/huawei/angler/proprietary/etc/data/netmgr_config.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/data/netmgr_config.xml:huawei \
    vendor/huawei/angler/proprietary/etc/data/qmi_config.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/data/qmi_config.xml:huawei \
    vendor/huawei/angler/proprietary/etc/flp.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/flp.conf:huawei \
    vendor/huawei/angler/proprietary/etc/gps.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/gps.conf:huawei \
    vendor/huawei/angler/proprietary/etc/izat.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/izat.conf:huawei \
    vendor/huawei/angler/proprietary/etc/lowi.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/lowi.conf:huawei \
    vendor/huawei/angler/proprietary/etc/permissions/cneapiclient.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/cneapiclient.xml:huawei \
    vendor/huawei/angler/proprietary/etc/permissions/com.android.omadm.service.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/com.android.omadm.service.xml:huawei \
    vendor/huawei/angler/proprietary/etc/permissions/com.google.widevine.software.drm.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/com.google.widevine.software.drm.xml:huawei \
    vendor/huawei/angler/proprietary/etc/permissions/qcrilhook.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/qcrilhook.xml:huawei \
    vendor/huawei/angler/proprietary/etc/pp_calib_data_SAMSUNG_S6E3HA3X01_5P7_1440P_CMD_DUAL0.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/pp_calib_data_SAMSUNG_S6E3HA3X01_5P7_1440P_CMD_DUAL0.xml:huawei \
    vendor/huawei/angler/proprietary/etc/sap.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/sap.conf:huawei \
    vendor/huawei/angler/proprietary/lib64/hw/audio.primary.msm8994.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/hw/audio.primary.msm8994.so:huawei \
    vendor/huawei/angler/proprietary/lib64/hw/gps.msm8994.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/hw/gps.msm8994.so:huawei \
    vendor/huawei/angler/proprietary/lib64/hw/nfc_nci.angler.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/hw/nfc_nci.angler.so:huawei \
    vendor/huawei/angler/proprietary/lib64/libfacelock_jni.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libfacelock_jni.so:huawei \
    vendor/huawei/angler/proprietary/lib64/libfilterpack_facedetect.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libfilterpack_facedetect.so:huawei \
    vendor/huawei/angler/proprietary/lib64/libgps.utils.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libgps.utils.so:huawei \
    vendor/huawei/angler/proprietary/lib64/libloc_api_v02.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libloc_api_v02.so:huawei \
    vendor/huawei/angler/proprietary/lib64/libloc_core.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libloc_core.so:huawei \
    vendor/huawei/angler/proprietary/lib64/libloc_ds_api.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libloc_ds_api.so:huawei \
    vendor/huawei/angler/proprietary/lib64/libloc_eng.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libloc_eng.so:huawei \
    vendor/huawei/angler/proprietary/lib64/libManufacture.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libManufacture.so:huawei \
    vendor/huawei/angler/proprietary/lib64/libspeexwrapper.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libspeexwrapper.so:huawei \
    vendor/huawei/angler/proprietary/lib64/libtinyxml.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libtinyxml.so:huawei \
    vendor/huawei/angler/proprietary/lib/hw/audio.primary.msm8994.so:$(TARGET_COPY_OUT_SYSTEM)/lib/hw/audio.primary.msm8994.so:huawei \
    vendor/huawei/angler/proprietary/lib/hw/camera.msm8994.so:$(TARGET_COPY_OUT_SYSTEM)/lib/hw/camera.msm8994.so:huawei \
    vendor/huawei/angler/proprietary/lib/hw/gps.msm8994.so:$(TARGET_COPY_OUT_SYSTEM)/lib/hw/gps.msm8994.so:huawei \
    vendor/huawei/angler/proprietary/lib/hw/nfc_nci.angler.so:$(TARGET_COPY_OUT_SYSTEM)/lib/hw/nfc_nci.angler.so:huawei \
    vendor/huawei/angler/proprietary/lib/libdmengine.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libdmengine.so:huawei \
    vendor/huawei/angler/proprietary/lib/libdmjavaplugin.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libdmjavaplugin.so:huawei \
    vendor/huawei/angler/proprietary/lib/libfilterpack_facedetect.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libfilterpack_facedetect.so:huawei \
    vendor/huawei/angler/proprietary/lib/libgps.utils.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libgps.utils.so:huawei \
    vendor/huawei/angler/proprietary/lib/libloc_api_v02.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libloc_api_v02.so:huawei \
    vendor/huawei/angler/proprietary/lib/libloc_core.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libloc_core.so:huawei \
    vendor/huawei/angler/proprietary/lib/libloc_ds_api.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libloc_ds_api.so:huawei \
    vendor/huawei/angler/proprietary/lib/libloc_eng.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libloc_eng.so:huawei \
    vendor/huawei/angler/proprietary/lib/libmmcamera_interface.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmmcamera_interface.so:huawei \
    vendor/huawei/angler/proprietary/lib/libmmjpeg_interface.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmmjpeg_interface.so:huawei \
    vendor/huawei/angler/proprietary/lib/libmm-qcamera.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmm-qcamera.so:huawei \
    vendor/huawei/angler/proprietary/lib/libqomx_core.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libqomx_core.so:huawei \
    vendor/huawei/angler/proprietary/lib/libspeexwrapper.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libspeexwrapper.so:huawei \
    vendor/huawei/angler/proprietary/lib/libtinyxml.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libtinyxml.so:huawei \
    vendor/huawei/angler/proprietary/lib/soundfx/libfmas.so:$(TARGET_COPY_OUT_SYSTEM)/lib/soundfx/libfmas.so:huawei \
    vendor/huawei/angler/proprietary/xbin/wlutil:$(TARGET_COPY_OUT_SYSTEM)/xbin/wlutil:huawei \
    vendor/huawei/angler/vendor/bin/diag_test_server:$(TARGET_COPY_OUT_VENDOR)/bin/diag_test_server:huawei \
    vendor/huawei/angler/vendor/bin/InputEventFind:$(TARGET_COPY_OUT_VENDOR)/bin/InputEventFind:huawei \
    vendor/huawei/angler/vendor/bin/mm-qcamera-daemon:$(TARGET_COPY_OUT_VENDOR)/bin/mm-qcamera-daemon:huawei \
    vendor/huawei/angler/vendor/bin/oem_qmi_server:$(TARGET_COPY_OUT_VENDOR)/bin/oem_qmi_server:huawei \
    vendor/huawei/angler/vendor/bin/qseecomd:$(TARGET_COPY_OUT_VENDOR)/bin/qseecomd:huawei \
    vendor/huawei/angler/vendor/bin/qti:$(TARGET_COPY_OUT_VENDOR)/bin/qti:huawei \
    vendor/huawei/angler/vendor/bin/sensortool.angler:$(TARGET_COPY_OUT_VENDOR)/bin/sensortool.angler:huawei \
    vendor/huawei/angler/vendor/bin/slim_daemon:$(TARGET_COPY_OUT_VENDOR)/bin/slim_daemon:huawei \
    vendor/huawei/angler/vendor/bin/sound_trigger_test:$(TARGET_COPY_OUT_VENDOR)/bin/sound_trigger_test:huawei \
    vendor/huawei/angler/vendor/etc/audio_effects.conf:$(TARGET_COPY_OUT_VENDOR)/etc/audio_effects.conf:huawei \
    vendor/huawei/angler/vendor/etc/audio_output_policy.conf:$(TARGET_COPY_OUT_VENDOR)/etc/audio_output_policy.conf:huawei \
    vendor/huawei/angler/vendor/etc/perf-profile0.conf:$(TARGET_COPY_OUT_VENDOR)/etc/perf-profile0.conf:huawei \
    vendor/huawei/angler/vendor/firmware/a420_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a420_pfp.fw:huawei \
    vendor/huawei/angler/vendor/firmware/a420_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a420_pm4.fw:huawei \
    vendor/huawei/angler/vendor/firmware/adsp.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b00:huawei \
    vendor/huawei/angler/vendor/firmware/adsp.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b01:huawei \
    vendor/huawei/angler/vendor/firmware/adsp.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b02:huawei \
    vendor/huawei/angler/vendor/firmware/adsp.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b03:huawei \
    vendor/huawei/angler/vendor/firmware/adsp.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b04:huawei \
    vendor/huawei/angler/vendor/firmware/adsp.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b05:huawei \
    vendor/huawei/angler/vendor/firmware/adsp.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b06:huawei \
    vendor/huawei/angler/vendor/firmware/adsp.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b07:huawei \
    vendor/huawei/angler/vendor/firmware/adsp.b08:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b08:huawei \
    vendor/huawei/angler/vendor/firmware/adsp.b09:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b09:huawei \
    vendor/huawei/angler/vendor/firmware/adsp.b10:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b10:huawei \
    vendor/huawei/angler/vendor/firmware/adsp.b11:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b11:huawei \
    vendor/huawei/angler/vendor/firmware/adsp.b12:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b12:huawei \
    vendor/huawei/angler/vendor/firmware/adsp.b13:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b13:huawei \
    vendor/huawei/angler/vendor/firmware/adsp.b14:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b14:huawei \
    vendor/huawei/angler/vendor/firmware/adsp.b15:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b15:huawei \
    vendor/huawei/angler/vendor/firmware/adsp.b16:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b16:huawei \
    vendor/huawei/angler/vendor/firmware/adsp.b17:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b17:huawei \
    vendor/huawei/angler/vendor/firmware/adsp.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.mdt:huawei \
    vendor/huawei/angler/vendor/firmware/BCM4358A3_RFSW.hcd:$(TARGET_COPY_OUT_VENDOR)/firmware/BCM4358A3_RFSW.hcd:huawei \
    vendor/huawei/angler/vendor/firmware/cpe.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe.b02:huawei \
    vendor/huawei/angler/vendor/firmware/cpe.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe.b04:huawei \
    vendor/huawei/angler/vendor/firmware/cpe.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe.b05:huawei \
    vendor/huawei/angler/vendor/firmware/cpe.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe.b06:huawei \
    vendor/huawei/angler/vendor/firmware/cpe.b08:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe.b08:huawei \
    vendor/huawei/angler/vendor/firmware/cpe.b10:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe.b10:huawei \
    vendor/huawei/angler/vendor/firmware/cpe.b11:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe.b11:huawei \
    vendor/huawei/angler/vendor/firmware/cpe.b12:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe.b12:huawei \
    vendor/huawei/angler/vendor/firmware/cpe.b14:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe.b14:huawei \
    vendor/huawei/angler/vendor/firmware/cpe.b16:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe.b16:huawei \
    vendor/huawei/angler/vendor/firmware/cpe.b18:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe.b18:huawei \
    vendor/huawei/angler/vendor/firmware/cpe.b20:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe.b20:huawei \
    vendor/huawei/angler/vendor/firmware/cpe.b21:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe.b21:huawei \
    vendor/huawei/angler/vendor/firmware/cpe.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe.mdt:huawei \
    vendor/huawei/angler/vendor/firmware/cpp_firmware_v1_1_1.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_1_1.fw:huawei \
    vendor/huawei/angler/vendor/firmware/cpp_firmware_v1_1_6.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_1_6.fw:huawei \
    vendor/huawei/angler/vendor/firmware/cpp_firmware_v1_2_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_2_0.fw:huawei \
    vendor/huawei/angler/vendor/firmware/cpp_firmware_v1_4_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_4_0.fw:huawei \
    vendor/huawei/angler/vendor/firmware/cpp_firmware_v1_6_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_6_0.fw:huawei \
    vendor/huawei/angler/vendor/firmware/cpp_firmware_v1_8_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_8_0.fw:huawei \
    vendor/huawei/angler/vendor/firmware/fingerpr.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/fingerpr.b00:huawei \
    vendor/huawei/angler/vendor/firmware/fingerpr.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/fingerpr.b01:huawei \
    vendor/huawei/angler/vendor/firmware/fingerpr.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/fingerpr.b02:huawei \
    vendor/huawei/angler/vendor/firmware/fingerpr.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/fingerpr.b03:huawei \
    vendor/huawei/angler/vendor/firmware/fingerpr.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/fingerpr.mdt:huawei \
    vendor/huawei/angler/vendor/firmware/fw_bcmdhd_apsta.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/fw_bcmdhd_apsta.bin:huawei \
    vendor/huawei/angler/vendor/firmware/fw_bcmdhd.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/fw_bcmdhd.bin:huawei \
    vendor/huawei/angler/vendor/firmware/leia_pfp_470.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/leia_pfp_470.fw:huawei \
    vendor/huawei/angler/vendor/firmware/leia_pm4_470.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/leia_pm4_470.fw:huawei \
    vendor/huawei/angler/vendor/firmware/libpn548ad_fw.so:$(TARGET_COPY_OUT_VENDOR)/firmware/libpn548ad_fw.so:huawei \
    vendor/huawei/angler/vendor/firmware/nano4x1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/nano4x1.bin:huawei \
    vendor/huawei/angler/vendor/firmware/venus.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.b00:huawei \
    vendor/huawei/angler/vendor/firmware/venus.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.b01:huawei \
    vendor/huawei/angler/vendor/firmware/venus.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.b02:huawei \
    vendor/huawei/angler/vendor/firmware/venus.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.b03:huawei \
    vendor/huawei/angler/vendor/firmware/venus.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.b04:huawei \
    vendor/huawei/angler/vendor/firmware/venus.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.mdt:huawei \
    vendor/huawei/angler/vendor/firmware/widevine.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/widevine.b00:huawei \
    vendor/huawei/angler/vendor/firmware/widevine.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/widevine.b01:huawei \
    vendor/huawei/angler/vendor/firmware/widevine.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/widevine.b02:huawei \
    vendor/huawei/angler/vendor/firmware/widevine.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/widevine.b03:huawei \
    vendor/huawei/angler/vendor/firmware/widevine.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/widevine.mdt:huawei \
    vendor/huawei/angler/vendor/lib64/egl/eglSubDriverAndroid.so:$(TARGET_COPY_OUT_VENDOR)/lib64/egl/eglSubDriverAndroid.so:huawei \
    vendor/huawei/angler/vendor/lib64/egl/libEGL_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib64/egl/libEGL_adreno.so:huawei \
    vendor/huawei/angler/vendor/lib64/egl/libGLESv1_CM_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib64/egl/libGLESv1_CM_adreno.so:huawei \
    vendor/huawei/angler/vendor/lib64/egl/libGLESv2_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib64/egl/libGLESv2_adreno.so:huawei \
    vendor/huawei/angler/vendor/lib64/egl/libq3dtools_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib64/egl/libq3dtools_adreno.so:huawei \
    vendor/huawei/angler/vendor/lib64/egl/libq3dtools_esx.so:$(TARGET_COPY_OUT_VENDOR)/lib64/egl/libq3dtools_esx.so:huawei \
    vendor/huawei/angler/vendor/lib64/hw/activity_recognition.angler.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/activity_recognition.angler.so:huawei \
    vendor/huawei/angler/vendor/lib64/hw/fingerprint.angler.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/fingerprint.angler.so:huawei \
    vendor/huawei/angler/vendor/lib64/hw/flp.default.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/flp.default.so:huawei \
    vendor/huawei/angler/vendor/lib64/hw/gatekeeper.msm8994.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/gatekeeper.msm8994.so:huawei \
    vendor/huawei/angler/vendor/lib64/hw/keystore.msm8994.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/keystore.msm8994.so:huawei \
    vendor/huawei/angler/vendor/lib64/hw/sensors.angler.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/sensors.angler.so:huawei \
    vendor/huawei/angler/vendor/lib64/hw/tof.vl6180.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/tof.vl6180.so:huawei \
    vendor/huawei/angler/vendor/lib64/libacdb-fts.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libacdb-fts.so:huawei \
    vendor/huawei/angler/vendor/lib64/libacdbloader.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libacdbloader.so:huawei \
    vendor/huawei/angler/vendor/lib64/libacdbmapper.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libacdbmapper.so:huawei \
    vendor/huawei/angler/vendor/lib64/libacdbrtac.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libacdbrtac.so:huawei \
    vendor/huawei/angler/vendor/lib64/libadiertac.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libadiertac.so:huawei \
    vendor/huawei/angler/vendor/lib64/libadreno_utils.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libadreno_utils.so:huawei \
    vendor/huawei/angler/vendor/lib64/libadsprpc.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libadsprpc.so:huawei \
    vendor/huawei/angler/vendor/lib64/libaudcal.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libaudcal.so:huawei \
    vendor/huawei/angler/vendor/lib64/libaudioalsa.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libaudioalsa.so:huawei \
    vendor/huawei/angler/vendor/lib64/libbccQTI.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libbccQTI.so:huawei \
    vendor/huawei/angler/vendor/lib64/libC2D2.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libC2D2.so:huawei \
    vendor/huawei/angler/vendor/lib64/libc2d30-a3xx.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libc2d30-a3xx.so:huawei \
    vendor/huawei/angler/vendor/lib64/libc2d30-a4xx.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libc2d30-a4xx.so:huawei \
    vendor/huawei/angler/vendor/lib64/libcallutils.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcallutils.so:huawei \
    vendor/huawei/angler/vendor/lib64/libCB.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libCB.so:huawei \
    vendor/huawei/angler/vendor/lib64/libcneapiclient.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcneapiclient.so:huawei \
    vendor/huawei/angler/vendor/lib64/libcne.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcne.so:huawei \
    vendor/huawei/angler/vendor/lib64/libconfigdb.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libconfigdb.so:huawei \
    vendor/huawei/angler/vendor/lib64/libdiag.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libdiag.so:huawei \
    vendor/huawei/angler/vendor/lib64/libdisp-aba.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libdisp-aba.so:huawei \
    vendor/huawei/angler/vendor/lib64/lib-dplmedia.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib-dplmedia.so:huawei \
    vendor/huawei/angler/vendor/lib64/libdrmfs.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libdrmfs.so:huawei \
    vendor/huawei/angler/vendor/lib64/libdrmtime.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libdrmtime.so:huawei \
    vendor/huawei/angler/vendor/lib64/libdsi_netctrl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libdsi_netctrl.so:huawei \
    vendor/huawei/angler/vendor/lib64/libdsutils.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libdsutils.so:huawei \
    vendor/huawei/angler/vendor/lib64/libEGL_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libEGL_adreno.so:huawei \
    vendor/huawei/angler/vendor/lib64/lib_fpc_tac_shared.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib_fpc_tac_shared.so:huawei \
    vendor/huawei/angler/vendor/lib64/libfrsdk.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libfrsdk.so:huawei \
    vendor/huawei/angler/vendor/lib64/libgeofence.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libgeofence.so:huawei \
    vendor/huawei/angler/vendor/lib64/libgsl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libgsl.so:huawei \
    vendor/huawei/angler/vendor/lib64/libhubconnection.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libhubconnection.so:huawei \
    vendor/huawei/angler/vendor/lib64/libhwgetnv.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libhwgetnv.so:huawei \
    vendor/huawei/angler/vendor/lib64/libhwnv.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libhwnv.so:huawei \
    vendor/huawei/angler/vendor/lib64/libhwsarcontrol.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libhwsarcontrol.so:huawei \
    vendor/huawei/angler/vendor/lib64/libidl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libidl.so:huawei \
    vendor/huawei/angler/vendor/lib64/libimscamera_jni.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libimscamera_jni.so:huawei \
    vendor/huawei/angler/vendor/lib64/lib-imsdpl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib-imsdpl.so:huawei \
    vendor/huawei/angler/vendor/lib64/libimsmedia_jni.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libimsmedia_jni.so:huawei \
    vendor/huawei/angler/vendor/lib64/lib-imsqimf.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib-imsqimf.so:huawei \
    vendor/huawei/angler/vendor/lib64/lib-imsrcscmclient.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib-imsrcscmclient.so:huawei \
    vendor/huawei/angler/vendor/lib64/lib-ims-rcscmjni.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib-ims-rcscmjni.so:huawei \
    vendor/huawei/angler/vendor/lib64/lib-imsrcscmservice.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib-imsrcscmservice.so:huawei \
    vendor/huawei/angler/vendor/lib64/lib-imsrcscm.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib-imsrcscm.so:huawei \
    vendor/huawei/angler/vendor/lib64/lib-imsrcs.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib-imsrcs.so:huawei \
    vendor/huawei/angler/vendor/lib64/lib-imsSDP.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib-imsSDP.so:huawei \
    vendor/huawei/angler/vendor/lib64/lib-imss.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib-imss.so:huawei \
    vendor/huawei/angler/vendor/lib64/lib-imsvt.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib-imsvt.so:huawei \
    vendor/huawei/angler/vendor/lib64/lib-imsxml.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib-imsxml.so:huawei \
    vendor/huawei/angler/vendor/lib64/libizat_core.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libizat_core.so:huawei \
    vendor/huawei/angler/vendor/lib64/libkmcrypto.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libkmcrypto.so:huawei \
    vendor/huawei/angler/vendor/lib64/liblbs_core.so:$(TARGET_COPY_OUT_VENDOR)/lib64/liblbs_core.so:huawei \
    vendor/huawei/angler/vendor/lib64/liblistensoundmodel2.so:$(TARGET_COPY_OUT_VENDOR)/lib64/liblistensoundmodel2.so:huawei \
    vendor/huawei/angler/vendor/lib64/libllvm-glnext.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libllvm-glnext.so:huawei \
    vendor/huawei/angler/vendor/lib64/libllvm-qcom.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libllvm-qcom.so:huawei \
    vendor/huawei/angler/vendor/lib64/liblowi_client.so:$(TARGET_COPY_OUT_VENDOR)/lib64/liblowi_client.so:huawei \
    vendor/huawei/angler/vendor/lib64/liblowi_wifihal.so:$(TARGET_COPY_OUT_VENDOR)/lib64/liblowi_wifihal.so:huawei \
    vendor/huawei/angler/vendor/lib64/liblqe.so:$(TARGET_COPY_OUT_VENDOR)/lib64/liblqe.so:huawei \
    vendor/huawei/angler/vendor/lib64/libmdmdetect.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmdmdetect.so:huawei \
    vendor/huawei/angler/vendor/lib64/libmdsprpc.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmdsprpc.so:huawei \
    vendor/huawei/angler/vendor/lib64/libmm-abl-oem.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmm-abl-oem.so:huawei \
    vendor/huawei/angler/vendor/lib64/libmm-abl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmm-abl.so:huawei \
    vendor/huawei/angler/vendor/lib64/libmm-als.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmm-als.so:huawei \
    vendor/huawei/angler/vendor/lib64/libmmcamera2_q3a_core.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmmcamera2_q3a_core.so:huawei \
    vendor/huawei/angler/vendor/lib64/libmmcamera2_sensor_debug.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmmcamera2_sensor_debug.so:huawei \
    vendor/huawei/angler/vendor/lib64/libmmcamera2_stats_algorithm.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmmcamera2_stats_algorithm.so:huawei \
    vendor/huawei/angler/vendor/lib64/libmm-disp-apis.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmm-disp-apis.so:huawei \
    vendor/huawei/angler/vendor/lib64/libmm-qdcm.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmm-qdcm.so:huawei \
    vendor/huawei/angler/vendor/lib64/libnetmgr.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libnetmgr.so:huawei \
    vendor/huawei/angler/vendor/lib64/libperipheral_client.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libperipheral_client.so:huawei \
    vendor/huawei/angler/vendor/lib64/libqcci_legacy.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqcci_legacy.so:huawei \
    vendor/huawei/angler/vendor/lib64/libqdi.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqdi.so:huawei \
    vendor/huawei/angler/vendor/lib64/libqdp.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqdp.so:huawei \
    vendor/huawei/angler/vendor/lib64/libqmi_cci.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqmi_cci.so:huawei \
    vendor/huawei/angler/vendor/lib64/libqmi_client_helper.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqmi_client_helper.so:huawei \
    vendor/huawei/angler/vendor/lib64/libqmi_client_qmux.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqmi_client_qmux.so:huawei \
    vendor/huawei/angler/vendor/lib64/libqmi_common_so.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqmi_common_so.so:huawei \
    vendor/huawei/angler/vendor/lib64/libqmi_csi.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqmi_csi.so:huawei \
    vendor/huawei/angler/vendor/lib64/libqmi_encdec.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqmi_encdec.so:huawei \
    vendor/huawei/angler/vendor/lib64/libqmi_oem_api.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqmi_oem_api.so:huawei \
    vendor/huawei/angler/vendor/lib64/libqmiservices.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqmiservices.so:huawei \
    vendor/huawei/angler/vendor/lib64/libqmi.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqmi.so:huawei \
    vendor/huawei/angler/vendor/lib64/libQSEEComAPI.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libQSEEComAPI.so:huawei \
    vendor/huawei/angler/vendor/lib64/libqti-perfd-client.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqti-perfd-client.so:huawei \
    vendor/huawei/angler/vendor/lib64/libquipc_os_api.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libquipc_os_api.so:huawei \
    vendor/huawei/angler/vendor/lib64/lib-rcsimssjni.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib-rcsimssjni.so:huawei \
    vendor/huawei/angler/vendor/lib64/lib-rcsjni.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib-rcsjni.so:huawei \
    vendor/huawei/angler/vendor/lib64/libril-qc-qmi-1.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libril-qc-qmi-1.so:huawei \
    vendor/huawei/angler/vendor/lib64/libril-qcril-hook-oem.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libril-qcril-hook-oem.so:huawei \
    vendor/huawei/angler/vendor/lib64/librpmb.so:$(TARGET_COPY_OUT_VENDOR)/lib64/librpmb.so:huawei \
    vendor/huawei/angler/vendor/lib64/librs_adreno_sha1.so:$(TARGET_COPY_OUT_VENDOR)/lib64/librs_adreno_sha1.so:huawei \
    vendor/huawei/angler/vendor/lib64/librs_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib64/librs_adreno.so:huawei \
    vendor/huawei/angler/vendor/lib64/libRSDriver_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libRSDriver_adreno.so:huawei \
    vendor/huawei/angler/vendor/lib64/lib-rtpcommon.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib-rtpcommon.so:huawei \
    vendor/huawei/angler/vendor/lib64/lib-rtpcore.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib-rtpcore.so:huawei \
    vendor/huawei/angler/vendor/lib64/lib-rtpdaemoninterface.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib-rtpdaemoninterface.so:huawei \
    vendor/huawei/angler/vendor/lib64/lib-rtpsl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib-rtpsl.so:huawei \
    vendor/huawei/angler/vendor/lib64/libscale.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libscale.so:huawei \
    vendor/huawei/angler/vendor/lib64/libsmemlog.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libsmemlog.so:huawei \
    vendor/huawei/angler/vendor/lib64/libssd.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libssd.so:huawei \
    vendor/huawei/angler/vendor/lib64/libsystem_health_mon.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libsystem_health_mon.so:huawei \
    vendor/huawei/angler/vendor/lib64/libthermalclient.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libthermalclient.so:huawei \
    vendor/huawei/angler/vendor/lib64/libthermalioctl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libthermalioctl.so:huawei \
    vendor/huawei/angler/vendor/lib64/libtime_genoff.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libtime_genoff.so:huawei \
    vendor/huawei/angler/vendor/lib64/libTimeService.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libTimeService.so:huawei \
    vendor/huawei/angler/vendor/lib64/libtzdrmgenprov.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libtzdrmgenprov.so:huawei \
    vendor/huawei/angler/vendor/lib64/libvoice-svc.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libvoice-svc.so:huawei \
    vendor/huawei/angler/vendor/lib64/libwms.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libwms.so:huawei \
    vendor/huawei/angler/vendor/lib64/libxml.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libxml.so:huawei \
    vendor/huawei/angler/vendor/lib64/mediadrm/libdrmclearkeyplugin.so:$(TARGET_COPY_OUT_VENDOR)/lib64/mediadrm/libdrmclearkeyplugin.so:huawei \
    vendor/huawei/angler/vendor/lib/egl/eglSubDriverAndroid.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/eglSubDriverAndroid.so:huawei \
    vendor/huawei/angler/vendor/lib/egl/libEGL_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libEGL_adreno.so:huawei \
    vendor/huawei/angler/vendor/lib/egl/libGLESv1_CM_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libGLESv1_CM_adreno.so:huawei \
    vendor/huawei/angler/vendor/lib/egl/libGLESv2_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libGLESv2_adreno.so:huawei \
    vendor/huawei/angler/vendor/lib/egl/libq3dtools_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libq3dtools_adreno.so:huawei \
    vendor/huawei/angler/vendor/lib/egl/libq3dtools_esx.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libq3dtools_esx.so:huawei \
    vendor/huawei/angler/vendor/lib/hw/activity_recognition.angler.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/activity_recognition.angler.so:huawei \
    vendor/huawei/angler/vendor/lib/hw/gatekeeper.msm8994.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/gatekeeper.msm8994.so:huawei \
    vendor/huawei/angler/vendor/lib/hw/keystore.msm8994.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/keystore.msm8994.so:huawei \
    vendor/huawei/angler/vendor/lib/hw/sensors.angler.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/sensors.angler.so:huawei \
    vendor/huawei/angler/vendor/lib/hw/sound_trigger.primary.msm8994.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/sound_trigger.primary.msm8994.so:huawei \
    vendor/huawei/angler/vendor/lib/libacdb-fts.so:$(TARGET_COPY_OUT_VENDOR)/lib/libacdb-fts.so:huawei \
    vendor/huawei/angler/vendor/lib/libacdbloader.so:$(TARGET_COPY_OUT_VENDOR)/lib/libacdbloader.so:huawei \
    vendor/huawei/angler/vendor/lib/libacdbmapper.so:$(TARGET_COPY_OUT_VENDOR)/lib/libacdbmapper.so:huawei \
    vendor/huawei/angler/vendor/lib/libacdbrtac.so:$(TARGET_COPY_OUT_VENDOR)/lib/libacdbrtac.so:huawei \
    vendor/huawei/angler/vendor/lib/libactuator_lc898212xd_camcorder.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_lc898212xd_camcorder.so:huawei \
    vendor/huawei/angler/vendor/lib/libactuator_lc898212xd_camera.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_lc898212xd_camera.so:huawei \
    vendor/huawei/angler/vendor/lib/libactuator_lc898212xd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_lc898212xd.so:huawei \
    vendor/huawei/angler/vendor/lib/libadiertac.so:$(TARGET_COPY_OUT_VENDOR)/lib/libadiertac.so:huawei \
    vendor/huawei/angler/vendor/lib/libadm.so:$(TARGET_COPY_OUT_VENDOR)/lib/libadm.so:huawei \
    vendor/huawei/angler/vendor/lib/libadpcmdec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libadpcmdec.so:huawei \
    vendor/huawei/angler/vendor/lib/libadreno_utils.so:$(TARGET_COPY_OUT_VENDOR)/lib/libadreno_utils.so:huawei \
    vendor/huawei/angler/vendor/lib/libadsprpc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libadsprpc.so:huawei \
    vendor/huawei/angler/vendor/lib/libaudcal.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaudcal.so:huawei \
    vendor/huawei/angler/vendor/lib/libaudioalsa.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaudioalsa.so:huawei \
    vendor/huawei/angler/vendor/lib/libbccQTI.so:$(TARGET_COPY_OUT_VENDOR)/lib/libbccQTI.so:huawei \
    vendor/huawei/angler/vendor/lib/libbt-vendor.so:$(TARGET_COPY_OUT_VENDOR)/lib/libbt-vendor.so:huawei \
    vendor/huawei/angler/vendor/lib/libC2D2.so:$(TARGET_COPY_OUT_VENDOR)/lib/libC2D2.so:huawei \
    vendor/huawei/angler/vendor/lib/libc2d30-a3xx.so:$(TARGET_COPY_OUT_VENDOR)/lib/libc2d30-a3xx.so:huawei \
    vendor/huawei/angler/vendor/lib/libc2d30-a4xx.so:$(TARGET_COPY_OUT_VENDOR)/lib/libc2d30-a4xx.so:huawei \
    vendor/huawei/angler/vendor/lib/libCB.so:$(TARGET_COPY_OUT_VENDOR)/lib/libCB.so:huawei \
    vendor/huawei/angler/vendor/lib/libchromatix_imx179_liteon_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx179_liteon_common.so:huawei \
    vendor/huawei/angler/vendor/lib/libchromatix_imx179_liteon_cpp_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx179_liteon_cpp_liveshot.so:huawei \
    vendor/huawei/angler/vendor/lib/libchromatix_imx179_liteon_cpp_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx179_liteon_cpp_preview.so:huawei \
    vendor/huawei/angler/vendor/lib/libchromatix_imx179_liteon_cpp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx179_liteon_cpp_snapshot.so:huawei \
    vendor/huawei/angler/vendor/lib/libchromatix_imx179_liteon_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx179_liteon_cpp_video.so:huawei \
    vendor/huawei/angler/vendor/lib/libchromatix_imx179_liteon_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx179_liteon_default_video.so:huawei \
    vendor/huawei/angler/vendor/lib/libchromatix_imx179_liteon_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx179_liteon_liveshot.so:huawei \
    vendor/huawei/angler/vendor/lib/libchromatix_imx179_liteon_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx179_liteon_postproc.so:huawei \
    vendor/huawei/angler/vendor/lib/libchromatix_imx179_liteon_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx179_liteon_preview.so:huawei \
    vendor/huawei/angler/vendor/lib/libchromatix_imx179_liteon_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx179_liteon_snapshot.so:huawei \
    vendor/huawei/angler/vendor/lib/libchromatix_imx179_liteon_video_binning.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx179_liteon_video_binning.so:huawei \
    vendor/huawei/angler/vendor/lib/libchromatix_imx179_sunny_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx179_sunny_common.so:huawei \
    vendor/huawei/angler/vendor/lib/libchromatix_imx179_sunny_cpp_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx179_sunny_cpp_liveshot.so:huawei \
    vendor/huawei/angler/vendor/lib/libchromatix_imx179_sunny_cpp_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx179_sunny_cpp_preview.so:huawei \
    vendor/huawei/angler/vendor/lib/libchromatix_imx179_sunny_cpp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx179_sunny_cpp_snapshot.so:huawei \
    vendor/huawei/angler/vendor/lib/libchromatix_imx179_sunny_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx179_sunny_cpp_video.so:huawei \
    vendor/huawei/angler/vendor/lib/libchromatix_imx179_sunny_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx179_sunny_default_video.so:huawei \
    vendor/huawei/angler/vendor/lib/libchromatix_imx179_sunny_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx179_sunny_liveshot.so:huawei \
    vendor/huawei/angler/vendor/lib/libchromatix_imx179_sunny_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx179_sunny_postproc.so:huawei \
    vendor/huawei/angler/vendor/lib/libchromatix_imx179_sunny_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx179_sunny_preview.so:huawei \
    vendor/huawei/angler/vendor/lib/libchromatix_imx179_sunny_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx179_sunny_snapshot.so:huawei \
    vendor/huawei/angler/vendor/lib/libchromatix_imx179_sunny_video_binning.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx179_sunny_video_binning.so:huawei \
    vendor/huawei/angler/vendor/lib/libchromatix_imx377_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx377_common.so:huawei \
    vendor/huawei/angler/vendor/lib/libchromatix_imx377_cpp_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx377_cpp_hfr_120.so:huawei \
    vendor/huawei/angler/vendor/lib/libchromatix_imx377_cpp_hfr_240.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx377_cpp_hfr_240.so:huawei \
    vendor/huawei/angler/vendor/lib/libchromatix_imx377_cpp_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx377_cpp_hfr_60.so:huawei \
    vendor/huawei/angler/vendor/lib/libchromatix_imx377_cpp_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx377_cpp_hfr_90.so:huawei \
    vendor/huawei/angler/vendor/lib/libchromatix_imx377_cpp_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx377_cpp_liveshot.so:huawei \
    vendor/huawei/angler/vendor/lib/libchromatix_imx377_cpp_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx377_cpp_preview.so:huawei \
    vendor/huawei/angler/vendor/lib/libchromatix_imx377_cpp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx377_cpp_snapshot.so:huawei \
    vendor/huawei/angler/vendor/lib/libchromatix_imx377_cpp_uhd_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx377_cpp_uhd_video.so:huawei \
    vendor/huawei/angler/vendor/lib/libchromatix_imx377_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx377_cpp_video.so:huawei \
    vendor/huawei/angler/vendor/lib/libchromatix_imx377_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx377_default_video.so:huawei \
    vendor/huawei/angler/vendor/lib/libchromatix_imx377_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx377_hfr_120.so:huawei \
    vendor/huawei/angler/vendor/lib/libchromatix_imx377_hfr_240.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx377_hfr_240.so:huawei \
    vendor/huawei/angler/vendor/lib/libchromatix_imx377_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx377_hfr_60.so:huawei \
    vendor/huawei/angler/vendor/lib/libchromatix_imx377_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx377_hfr_90.so:huawei \
    vendor/huawei/angler/vendor/lib/libchromatix_imx377_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx377_liveshot.so:huawei \
    vendor/huawei/angler/vendor/lib/libchromatix_imx377_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx377_postproc.so:huawei \
    vendor/huawei/angler/vendor/lib/libchromatix_imx377_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx377_preview.so:huawei \
    vendor/huawei/angler/vendor/lib/libchromatix_imx377_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx377_snapshot.so:huawei \
    vendor/huawei/angler/vendor/lib/libcneapiclient.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcneapiclient.so:huawei \
    vendor/huawei/angler/vendor/lib/libcne.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcne.so:huawei \
    vendor/huawei/angler/vendor/lib/libconfigdb.so:$(TARGET_COPY_OUT_VENDOR)/lib/libconfigdb.so:huawei \
    vendor/huawei/angler/vendor/lib/libdiag.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdiag.so:huawei \
    vendor/huawei/angler/vendor/lib/lib-dplmedia.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib-dplmedia.so:huawei \
    vendor/huawei/angler/vendor/lib/libdrmfs.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdrmfs.so:huawei \
    vendor/huawei/angler/vendor/lib/libdrmtime.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdrmtime.so:huawei \
    vendor/huawei/angler/vendor/lib/libdsi_netctrl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdsi_netctrl.so:huawei \
    vendor/huawei/angler/vendor/lib/libdsutils.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdsutils.so:huawei \
    vendor/huawei/angler/vendor/lib/libflash_pmic.so:$(TARGET_COPY_OUT_VENDOR)/lib/libflash_pmic.so:huawei \
    vendor/huawei/angler/vendor/lib/libfrsdk.so:$(TARGET_COPY_OUT_VENDOR)/lib/libfrsdk.so:huawei \
    vendor/huawei/angler/vendor/lib/libgoog_eis_armeabi-v7a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libgoog_eis_armeabi-v7a.so:huawei \
    vendor/huawei/angler/vendor/lib/libgoog_rownr.so:$(TARGET_COPY_OUT_VENDOR)/lib/libgoog_rownr.so:huawei \
    vendor/huawei/angler/vendor/lib/libgsl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libgsl.so:huawei \
    vendor/huawei/angler/vendor/lib/libhubconnection.so:$(TARGET_COPY_OUT_VENDOR)/lib/libhubconnection.so:huawei \
    vendor/huawei/angler/vendor/lib/libidl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libidl.so:huawei \
    vendor/huawei/angler/vendor/lib/libimscamera_jni.so:$(TARGET_COPY_OUT_VENDOR)/lib/libimscamera_jni.so:huawei \
    vendor/huawei/angler/vendor/lib/lib-imsdpl.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib-imsdpl.so:huawei \
    vendor/huawei/angler/vendor/lib/libimsmedia_jni.so:$(TARGET_COPY_OUT_VENDOR)/lib/libimsmedia_jni.so:huawei \
    vendor/huawei/angler/vendor/lib/lib-imsqimf.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib-imsqimf.so:huawei \
    vendor/huawei/angler/vendor/lib/lib-imsrcscmclient.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib-imsrcscmclient.so:huawei \
    vendor/huawei/angler/vendor/lib/lib-ims-rcscmjni.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib-ims-rcscmjni.so:huawei \
    vendor/huawei/angler/vendor/lib/lib-imsrcscmservice.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib-imsrcscmservice.so:huawei \
    vendor/huawei/angler/vendor/lib/lib-imsrcscm.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib-imsrcscm.so:huawei \
    vendor/huawei/angler/vendor/lib/lib-imsrcs.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib-imsrcs.so:huawei \
    vendor/huawei/angler/vendor/lib/lib-imsSDP.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib-imsSDP.so:huawei \
    vendor/huawei/angler/vendor/lib/lib-imss.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib-imss.so:huawei \
    vendor/huawei/angler/vendor/lib/lib-imsvt.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib-imsvt.so:huawei \
    vendor/huawei/angler/vendor/lib/lib-imsxml.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib-imsxml.so:huawei \
    vendor/huawei/angler/vendor/lib/libjpegdhw.so:$(TARGET_COPY_OUT_VENDOR)/lib/libjpegdhw.so:huawei \
    vendor/huawei/angler/vendor/lib/libjpegdmahw.so:$(TARGET_COPY_OUT_VENDOR)/lib/libjpegdmahw.so:huawei \
    vendor/huawei/angler/vendor/lib/libjpegehw.so:$(TARGET_COPY_OUT_VENDOR)/lib/libjpegehw.so:huawei \
    vendor/huawei/angler/vendor/lib/libkmcrypto.so:$(TARGET_COPY_OUT_VENDOR)/lib/libkmcrypto.so:huawei \
    vendor/huawei/angler/vendor/lib/liblistensoundmodel2.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblistensoundmodel2.so:huawei \
    vendor/huawei/angler/vendor/lib/libllvm-glnext.so:$(TARGET_COPY_OUT_VENDOR)/lib/libllvm-glnext.so:huawei \
    vendor/huawei/angler/vendor/lib/libllvm-qcom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libllvm-qcom.so:huawei \
    vendor/huawei/angler/vendor/lib/liblqe.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblqe.so:huawei \
    vendor/huawei/angler/vendor/lib/libmdmdetect.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmdmdetect.so:huawei \
    vendor/huawei/angler/vendor/lib/libmdsprpc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmdsprpc.so:huawei \
    vendor/huawei/angler/vendor/lib/libmm-abl-oem.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmm-abl-oem.so:huawei \
    vendor/huawei/angler/vendor/lib/libmm-abl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmm-abl.so:huawei \
    vendor/huawei/angler/vendor/lib/libmm-als.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmm-als.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera2_c2d_module.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_c2d_module.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera2_cpp_module.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_cpp_module.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera2_frame_algorithm.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_frame_algorithm.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera2_iface_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_iface_modules.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera2_imglib_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_imglib_modules.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera2_isp_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_isp_modules.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera2_is.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_is.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera2_pp_buf_mgr.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_pp_buf_mgr.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera2_pproc_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_pproc_modules.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera2_q3a_core.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_q3a_core.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera2_sensor_debug.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_sensor_debug.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera2_sensor_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_sensor_modules.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera2_stats_algorithm.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_stats_algorithm.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera2_stats_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_stats_modules.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera2_vpe_module.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_vpe_module.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera2_wnr_module.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_wnr_module.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera_cac2_lib.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_cac2_lib.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera_dw9761b_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_dw9761b_eeprom.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera_eeprom_util.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_eeprom_util.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera_eztune_module.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_eztune_module.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera_faceproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_faceproc.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera_imglib.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_imglib.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera_imx179_liteon.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_imx179_liteon.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera_imx179_sunny.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_imx179_sunny.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera_imx377.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_imx377.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera_isp_abcc44.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_abcc44.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera_isp_abf44.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_abf44.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera_isp_bcc44.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_bcc44.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera_isp_be_stats44.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_be_stats44.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera_isp_bf_scale_stats46.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_bf_scale_stats46.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera_isp_bf_stats44.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_bf_stats44.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera_isp_bg_stats46.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_bg_stats46.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera_isp_bhist_stats44.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_bhist_stats44.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera_isp_bpc44.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_bpc44.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera_isp_chroma_enhan40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_chroma_enhan40.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera_isp_chroma_suppress40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_chroma_suppress40.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera_isp_clamp_encoder40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_clamp_encoder40.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera_isp_clamp_video40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_clamp_video40.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera_isp_clamp_viewfinder40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_clamp_viewfinder40.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera_isp_clf46.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_clf46.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera_isp_color_correct46.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_color_correct46.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera_isp_color_xform_encoder46.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_color_xform_encoder46.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera_isp_color_xform_video46.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_color_xform_video46.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera_isp_color_xform_viewfinder46.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_color_xform_viewfinder46.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera_isp_cs_stats46.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_cs_stats46.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera_isp_demosaic44.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_demosaic44.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera_isp_demux40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_demux40.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera_isp_fovcrop_encoder46.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_fovcrop_encoder46.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera_isp_fovcrop_video46.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_fovcrop_video46.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera_isp_fovcrop_viewfinder46.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_fovcrop_viewfinder46.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera_isp_gamma44.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_gamma44.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera_isp_gic46.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_gic46.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera_isp_gtm46.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_gtm46.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera_isp_hdr46.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_hdr46.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera_isp_hdr_be_stats46.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_hdr_be_stats46.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera_isp_ihist_stats46.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_ihist_stats46.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera_isp_linearization40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_linearization40.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera_isp_ltm44.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_ltm44.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera_isp_mce40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_mce40.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera_isp_mesh_rolloff44.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_mesh_rolloff44.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera_isp_pedestal_correct46.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_pedestal_correct46.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera_isp_rs_stats46.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_rs_stats46.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera_isp_scaler_encoder46.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_scaler_encoder46.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera_isp_scaler_video46.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_scaler_video46.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera_isp_scaler_viewfinder46.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_scaler_viewfinder46.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera_isp_sce40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_sce40.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera_isp_sub_module.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_sub_module.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera_isp_wb46.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_wb46.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera_m24c64s_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_m24c64s_eeprom.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera_pdafcamif.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_pdafcamif.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera_pdaf.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_pdaf.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera_ppbase_module.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_ppbase_module.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera_sony_imx179_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_sony_imx179_eeprom.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera_tintless_algo.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_tintless_algo.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera_tintless_bg_pca_algo.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_tintless_bg_pca_algo.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmcamera_vpu_module.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_vpu_module.so:huawei \
    vendor/huawei/angler/vendor/lib/libmm-disp-apis.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmm-disp-apis.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmipl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmipl.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmjpeg.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmjpeg.so:huawei \
    vendor/huawei/angler/vendor/lib/libmm-qdcm.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmm-qdcm.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmqjpeg_codec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmqjpeg_codec.so:huawei \
    vendor/huawei/angler/vendor/lib/libmmqjpegdma.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmqjpegdma.so:huawei \
    vendor/huawei/angler/vendor/lib/libnetmgr.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnetmgr.so:huawei \
    vendor/huawei/angler/vendor/lib/liboemcamera.so:$(TARGET_COPY_OUT_VENDOR)/lib/liboemcamera.so:huawei \
    vendor/huawei/angler/vendor/lib/liboemcrypto.so:$(TARGET_COPY_OUT_VENDOR)/lib/liboemcrypto.so:huawei \
    vendor/huawei/angler/vendor/lib/libperipheral_client.so:$(TARGET_COPY_OUT_VENDOR)/lib/libperipheral_client.so:huawei \
    vendor/huawei/angler/vendor/lib/libqcci_legacy.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqcci_legacy.so:huawei \
    vendor/huawei/angler/vendor/lib/libqdi.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqdi.so:huawei \
    vendor/huawei/angler/vendor/lib/libqdp.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqdp.so:huawei \
    vendor/huawei/angler/vendor/lib/libqmi_cci.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi_cci.so:huawei \
    vendor/huawei/angler/vendor/lib/libqmi_client_helper.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi_client_helper.so:huawei \
    vendor/huawei/angler/vendor/lib/libqmi_client_qmux.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi_client_qmux.so:huawei \
    vendor/huawei/angler/vendor/lib/libqmi_common_so.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi_common_so.so:huawei \
    vendor/huawei/angler/vendor/lib/libqmi_csi.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi_csi.so:huawei \
    vendor/huawei/angler/vendor/lib/libqmi_encdec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi_encdec.so:huawei \
    vendor/huawei/angler/vendor/lib/libqmiservices.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmiservices.so:huawei \
    vendor/huawei/angler/vendor/lib/libqmi.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi.so:huawei \
    vendor/huawei/angler/vendor/lib/libqomx_jpegdec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqomx_jpegdec.so:huawei \
    vendor/huawei/angler/vendor/lib/libqomx_jpegenc_pipe.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqomx_jpegenc_pipe.so:huawei \
    vendor/huawei/angler/vendor/lib/libqomx_jpegenc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqomx_jpegenc.so:huawei \
    vendor/huawei/angler/vendor/lib/libQSEEComAPI.so:$(TARGET_COPY_OUT_VENDOR)/lib/libQSEEComAPI.so:huawei \
    vendor/huawei/angler/vendor/lib/libqti-perfd-client.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqti-perfd-client.so:huawei \
    vendor/huawei/angler/vendor/lib/lib-rcsimssjni.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib-rcsimssjni.so:huawei \
    vendor/huawei/angler/vendor/lib/lib-rcsjni.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib-rcsjni.so:huawei \
    vendor/huawei/angler/vendor/lib/libril-qc-qmi-1.so:$(TARGET_COPY_OUT_VENDOR)/lib/libril-qc-qmi-1.so:huawei \
    vendor/huawei/angler/vendor/lib/libril-qcril-hook-oem.so:$(TARGET_COPY_OUT_VENDOR)/lib/libril-qcril-hook-oem.so:huawei \
    vendor/huawei/angler/vendor/lib/librpmb.so:$(TARGET_COPY_OUT_VENDOR)/lib/librpmb.so:huawei \
    vendor/huawei/angler/vendor/lib/librs_adreno_sha1.so:$(TARGET_COPY_OUT_VENDOR)/lib/librs_adreno_sha1.so:huawei \
    vendor/huawei/angler/vendor/lib/librs_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib/librs_adreno.so:huawei \
    vendor/huawei/angler/vendor/lib/libRSDriver_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib/libRSDriver_adreno.so:huawei \
    vendor/huawei/angler/vendor/lib/librs.rnr_downscale.so:$(TARGET_COPY_OUT_VENDOR)/lib/librs.rnr_downscale.so:huawei \
    vendor/huawei/angler/vendor/lib/librs.rnr_process.so:$(TARGET_COPY_OUT_VENDOR)/lib/librs.rnr_process.so:huawei \
    vendor/huawei/angler/vendor/lib/lib-rtpcommon.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib-rtpcommon.so:huawei \
    vendor/huawei/angler/vendor/lib/lib-rtpcore.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib-rtpcore.so:huawei \
    vendor/huawei/angler/vendor/lib/lib-rtpdaemoninterface.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib-rtpdaemoninterface.so:huawei \
    vendor/huawei/angler/vendor/lib/lib-rtpsl.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib-rtpsl.so:huawei \
    vendor/huawei/angler/vendor/lib/libscale.so:$(TARGET_COPY_OUT_VENDOR)/lib/libscale.so:huawei \
    vendor/huawei/angler/vendor/lib/libsmemlog.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsmemlog.so:huawei \
    vendor/huawei/angler/vendor/lib/libssd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libssd.so:huawei \
    vendor/huawei/angler/vendor/lib/libsystem_health_mon.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsystem_health_mon.so:huawei \
    vendor/huawei/angler/vendor/lib/libthermalclient.so:$(TARGET_COPY_OUT_VENDOR)/lib/libthermalclient.so:huawei \
    vendor/huawei/angler/vendor/lib/libtime_genoff.so:$(TARGET_COPY_OUT_VENDOR)/lib/libtime_genoff.so:huawei \
    vendor/huawei/angler/vendor/lib/libTimeService.so:$(TARGET_COPY_OUT_VENDOR)/lib/libTimeService.so:huawei \
    vendor/huawei/angler/vendor/lib/libtzdrmgenprov.so:$(TARGET_COPY_OUT_VENDOR)/lib/libtzdrmgenprov.so:huawei \
    vendor/huawei/angler/vendor/lib/libvoice-svc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libvoice-svc.so:huawei \
    vendor/huawei/angler/vendor/lib/libwms.so:$(TARGET_COPY_OUT_VENDOR)/lib/libwms.so:huawei \
    vendor/huawei/angler/vendor/lib/libwvdrm_L1.so:$(TARGET_COPY_OUT_VENDOR)/lib/libwvdrm_L1.so:huawei \
    vendor/huawei/angler/vendor/lib/libWVStreamControlAPI_L1.so:$(TARGET_COPY_OUT_VENDOR)/lib/libWVStreamControlAPI_L1.so:huawei \
    vendor/huawei/angler/vendor/lib/libxml.so:$(TARGET_COPY_OUT_VENDOR)/lib/libxml.so:huawei \
    vendor/huawei/angler/vendor/lib/mediadrm/libdrmclearkeyplugin.so:$(TARGET_COPY_OUT_VENDOR)/lib/mediadrm/libdrmclearkeyplugin.so:huawei \
    vendor/huawei/angler/vendor/lib/mediadrm/libwvdrmengine.so:$(TARGET_COPY_OUT_VENDOR)/lib/mediadrm/libwvdrmengine.so:huawei \
    vendor/huawei/angler/vendor/media/LMspeed_508.emd:$(TARGET_COPY_OUT_VENDOR)/media/LMspeed_508.emd:huawei \
    vendor/huawei/angler/vendor/media/PFFprec_600.emd:$(TARGET_COPY_OUT_VENDOR)/media/PFFprec_600.emd:huawei \
    vendor/huawei/angler/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.8/landmark_group_meta_data.bin:$(TARGET_COPY_OUT_VENDOR)/pittpatt/models/detection/multi_pose_face_landmark_detectors.8/landmark_group_meta_data.bin:huawei \
    vendor/huawei/angler/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.8/left_eye-y0-yi45-p0-pi45-r0-ri20.lg_32-tree7-wmd.bin:$(TARGET_COPY_OUT_VENDOR)/pittpatt/models/detection/multi_pose_face_landmark_detectors.8/left_eye-y0-yi45-p0-pi45-r0-ri20.lg_32-tree7-wmd.bin:huawei \
    vendor/huawei/angler/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.8/nose_base-y0-yi45-p0-pi45-r0-ri20.lg_32-tree7-wmd.bin:$(TARGET_COPY_OUT_VENDOR)/pittpatt/models/detection/multi_pose_face_landmark_detectors.8/nose_base-y0-yi45-p0-pi45-r0-ri20.lg_32-tree7-wmd.bin:huawei \
    vendor/huawei/angler/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.8/right_eye-y0-yi45-p0-pi45-r0-ri20.lg_32-3-tree7-wmd.bin:$(TARGET_COPY_OUT_VENDOR)/pittpatt/models/detection/multi_pose_face_landmark_detectors.8/right_eye-y0-yi45-p0-pi45-r0-ri20.lg_32-3-tree7-wmd.bin:huawei \
    vendor/huawei/angler/vendor/pittpatt/models/detection/yaw_roll_face_detectors.7.1/head-y0-yi45-p0-pi45-r0-ri30.4a-v24-tree7-2-wmd.bin:$(TARGET_COPY_OUT_VENDOR)/pittpatt/models/detection/yaw_roll_face_detectors.7.1/head-y0-yi45-p0-pi45-r0-ri30.4a-v24-tree7-2-wmd.bin:huawei \
    vendor/huawei/angler/vendor/pittpatt/models/detection/yaw_roll_face_detectors.7.1/head-y0-yi45-p0-pi45-rn30-ri30.5-v24-tree7-2-wmd.bin:$(TARGET_COPY_OUT_VENDOR)/pittpatt/models/detection/yaw_roll_face_detectors.7.1/head-y0-yi45-p0-pi45-rn30-ri30.5-v24-tree7-2-wmd.bin:huawei \
    vendor/huawei/angler/vendor/pittpatt/models/detection/yaw_roll_face_detectors.7.1/head-y0-yi45-p0-pi45-rp30-ri30.5-v24-tree7-2-wmd.bin:$(TARGET_COPY_OUT_VENDOR)/pittpatt/models/detection/yaw_roll_face_detectors.7.1/head-y0-yi45-p0-pi45-rp30-ri30.5-v24-tree7-2-wmd.bin:huawei \
    vendor/huawei/angler/vendor/pittpatt/models/detection/yaw_roll_face_detectors.7.1/pose-r.8.1.bin:$(TARGET_COPY_OUT_VENDOR)/pittpatt/models/detection/yaw_roll_face_detectors.7.1/pose-r.8.1.bin:huawei \
    vendor/huawei/angler/vendor/pittpatt/models/detection/yaw_roll_face_detectors.7.1/pose-y-r.8.1.bin:$(TARGET_COPY_OUT_VENDOR)/pittpatt/models/detection/yaw_roll_face_detectors.7.1/pose-y-r.8.1.bin:huawei \
    vendor/huawei/angler/vendor/pittpatt/models/recognition/face.face.y0-y0-71-N-tree_7-wmd.bin:$(TARGET_COPY_OUT_VENDOR)/pittpatt/models/recognition/face.face.y0-y0-71-N-tree_7-wmd.bin:huawei

